import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import Navbar from "./components/elements/Navbar";
import Footer from "./components/elements/Footer";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <Navbar />
      <main>
        <body className="bg-body flex flex-col gap-y-20 overflow-hidden overflow-y-auto md:gap-y-32">
          {children}
        </body>
      </main>
      <Footer />
    </html>
  );
}
